version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
  
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8000:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: mongodb://root:example@mongo:27017
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes: 
      - "./frontend:/app:cached"
      - "./frontend/node_modules:/app/node_modules:cached"
    environment:
      - NODE_ENV=development

volumes:
  db-data: